### ISSUE TITLE
Error: Failed to initialize miner: clGetPlatformIDs

### ISSUE THREAD

**Issue by b4dg0d** [tomkha/nq-miner#10]
Hi,
I used https://hub.shortnim.me/setupMiner for setting up the program and installed everything as told.
I get this error after executing ./start_gpu.sh as root:

------------------------START Miner----------------------
[I 19:32:39] NQMiner: NQ Miner 0.99.7 OpenCL starting
Error: Failed to initialize miner: clGetPlatformIDs
    at new NativeMiner (/snapshot/nq-miner/src/NativeMiner.js:0:0)
    at /snapshot/nq-miner/index.js:0:0
    at Object.<anonymous> (/snapshot/nq-miner/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (internal/bootstrap/node.js:320:19)
------------------------END Miner----------------------
Something went wrong or you exited

What's the issue? Do I lack some dependencies? Do I have to install something manually? It looks like a runtime error but honestly idk.

Feel free to help. Thanks in advance!

**Comment by tomkha** [comment]
it looks like you don't have OpenCL platform available. What's your GPU/drivers versions?
also try running `clinfo` to find out details

**Comment by b4dg0d** [comment]
Hi,
Here's some information about my system: https://pastebin.com/FVvUcHNJ
I also installed amdpro-gpu drivers. But still, clinfo shows 0.

**Comment by tomkha** [comment]
yeah, you need to figure out how to install drivers that support OpenCL

**Comment by Albermonte** [comment]
Using [ROCm](https://rocmdocs.amd.com/en/latest/) might solve this

**Comment by tE3m** [comment]
In case anyone is still running into this issue: On Linux, when installing the AMD drivers, you'll need to set `--opencl=rocr,legacy` to include support for OpenCL. [documentation](https://amdgpu-install.readthedocs.io/en/latest/install-script.html#specifying-an-opencl-implementation)
