### ISSUE TITLE
How to recompile nqminer

### ISSUE THREAD

**Issue by njm21** [tomkha/nq-miner#7]
ubuntu 18.04
now run ./release_linux.sh   
What is the reason for such a mistake?

make: Entering directory '/home/hqw/nq-miner-app/nq-miner-0.99.7/build'
  RULE binding_gyp_nimiq_miner_cuda_target_CUDA_compiler_0 Release/obj.target/nimiq_miner_cuda/geni/argon2d.o
/bin/sh: 1: nvcc: not found
nimiq_miner_cuda.target.mk:10: recipe for target 'Release/obj.target/nimiq_miner_cuda/geni/argon2d.o' failed
make: *** [Release/obj.target/nimiq_miner_cuda/geni/argon2d.o] Error 127
make: Leaving directory '/home/hqw/nq-miner-app/nq-miner-0.99.7/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hqw/nq-miner-app/nq-miner-0.99.7/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-130-generic
gyp ERR! command "/usr/bin/node" "/home/hqw/nq-miner-app/nq-miner-0.99.7/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hqw/nq-miner-app/nq-miner-0.99.7
gyp ERR! node -v v10.23.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
error Command failed with exit code 1.

**Comment by tomkha** [comment]
Do you have CUDA installed? If so you must have nvcc somewhere in /usr/local/cuda/bin/
Also run the following before release_linux.sh

`export CUDA_PATH=/usr/local/cuda`
